
* ways of implemeting
I'm thinking about using the quality of humen spirit as the essential core of this thing.
clever man know that books are good: they know what books are bad.
not that clever people(like me hhh) don't know, they kind of mixed good books with bad books(for good books will let every one like it)
but as not that clever people slowly follows clever people, they will become noticed about the good and bad of books.
although you might thought about not that clever people will mix clever people with not that clever people(which certainly will happen because i don't like what so called educational background)
but the result will tend to make them touch more clever peoples.  either they accidentally never seen a clever people in 80 years of life, 
or they will see some and see more and more through his/hers "not clever following people's followed clever people".

hope it will work.

* this is a story about informations. 
We all know that books carried informations, like other spoken languages.  
It's very reasonable to share good books with others, to get these beautiful informations.
but although have many ancestors tried using "books gather collections" or "libraries" to spread out,
it's not in a very powerful way.
I think it's time for humen to develop a new way.
a new way to touch humen spirit as quickly as possible, through the beauty of books.  

i believe that if this works, humen's average intellectual will go up to a new step.  
by making youngs touch great books earlier, know more things while they are still in hunger, 
more youngs will change from "be taught a little in school with poor knowledges and bad teachers" to what we call "clever", "rational", "open mided".
for knowledge is not magic. every knowledge can be taught. no one is born clever. it's the book that make them seem more clever. 
it's only that they learned things earlier: learned how to learn earlier, learned how to study earlier, learned how to do research earlier, learned how to teach people earlier.  

